version: "3.5"

services:
  database:
    image: amsterdam/postgres11
    ports:
      - 5432
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  x-app: &app
    build:
      context: .
      target: app
    ports:
    - 8000
    - 8001
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./deploy:/deploy
    links:
    - database
    environment: &app_environment
      DATAPUNT_API_URL: "https://api.data.amsterdam.nl/"
      SECRET_KEY: "dev"
      OBJECTSTORE_PASSWORD: "insecure"
      # Gatekeeper listens on port 8000 and serves as a proxy for UWSGI
      PROXY_CLIENT_ID: "${GATEKEEPER_CLIENT_ID}"
      PROXY_CLIENT_SECRET: "${GATEKEEPER_CLIENT_SECRET}"
      PROXY_ENCRYPTION_KEY: "${GATEKEEPER_ENCRYPTION_KEY}"
      PROXY_LISTEN: "${GATEKEEPER_LISTEN}"
      PROXY_UPSTREAM_URL: "${GATEKEEPER_UPSTREAM_URL}"
      PROXY_DISCOVERY_URL: "${GATEKEEPER_DISCOVERY_URL}"
      PROXY_REDIRECTION_URL: "${GATEKEEPER_REDIRECTION_URL}"
      OBJECTSTORE_UPLOAD_CONTAINER_NAME: dev


  app:
    <<: *app
    image: repo.data.amsterdam.nl/datapunt/blackspots:${VERSION:-latest}

  dev:
    <<: *app
    build:
      context: .
      target: dev
    environment:
      <<: *app_environment
      DEBUG: 1
    command: "./manage.py runserver 0.0.0.0:8000"

  update_stadsdeel_errors:
    build:
      context: .
      target: app
    links:
      - database
    environment:
      CRET_KEY: "dev"
      TABASE_NAME: "dev"
      TABASE_USER: "dev"
      TABASE_PASSWORD: "dev"
    entrypoint: /deploy/wait-for-it.sh database:5432 --
    command: deploy/docker-update-stadsdelen.sh

  test:
    build:
      context: .
      target: tests
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./deploy:/deploy
    environment:
      SECRET_KEY: "tests"
      AUTHORIZATION_TOKEN: "dev"
      DJANGO_SETTINGS_MODULE: "main.settings"
      OBJECTSTORE_UPLOAD_CONTAINER_NAME: test
      PYTEST_ADDOPTS:
      PYTHONBREAKPOINT:
    depends_on:
      - database
    entrypoint: /deploy/wait-for-it.sh database:5432 --
    command: pytest
