version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5409:5432"
    environment:
      POSTGRES_DB: blackspots
      POSTGRES_USER: blackspots
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  web:
    build: ./api
    ports:
    - "8000:8000"
    - "8001:8001"
    links:
    - database
    environment:
    - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    - SECRET_KEY=insecure
    - DATABASE_NAME=blackspots
    - DATABASE_USER=blackspots
    - DATABASE_PASSWORD=insecure
    - OBJECTSTORE_PASSWORD=insecure
    - CONSUL_HOST=${CONSUL_HOST:-notset}
    - CONSUL_PORT=${CONSUL_PORT:-8500}
    # Gatekeeper listens on port 8000 and serves as a proxy for UWSGI
    - UWSGI_HTTP=:8001
    - UWSGI_MODULE=settings.wsgi:application
    - UWSGI_MASTER=1
    - UWSGI_STATIC_MAP=/static=/static
    - PROXY_CLIENT_ID=${GATEKEEPER_CLIENT_ID}
    - PROXY_CLIENT_SECRET=${GATEKEEPER_CLIENT_SECRET}
    - PROXY_ENCRYPTION_KEY=${GATEKEEPER_ENCRYPTION_KEY}
    - PROXY_LISTEN=${GATEKEEPER_LISTEN}
    - PROXY_UPSTREAM_URL=${GATEKEEPER_UPSTREAM_URL}
    - PROXY_DISCOVERY_URL=${GATEKEEPER_DISCOVERY_URL}
    - PROXY_REDIRECTION_URL=${GATEKEEPER_REDIRECTION_URL}

  update_stadsdeel_errors:
    build: ./api
    links:
      - database
    environment:
      - SECRET_KEY=insecure
      - DATABASE_NAME=blackspots
      - DATABASE_USER=blackspots
      - DATABASE_PASSWORD=insecure
    command: deploy/docker-update-stadsdelen.sh

  migrate:
    build: ./api
    links:
      - database
    environment:
      - SECRET_KEY=insecure
      - DATABASE_NAME=blackspots
      - DATABASE_USER=blackspots
      - DATABASE_PASSWORD=insecure
    command: deploy/docker-migrate.sh